console.log("Oi, meu nome é Ruan")
console.log('Vou me tornar um desenvolvedor!')
console.log(`Template strings`)
console.log("infinity")
console.log(Infinity)
console.log(typeof("Oi, meu nome é Ruan"))
console.log(typeof('Vou me tornar um desenvolvedor!'))
console.log(typeof(`Template strings`))
console.log(typeof("infinity"))
console.log(typeof(Infinity))