console.log(5 > 3 && 3 == 3)
console.log(5 > 3 || 3 == 1)
console.log(3 == 3 && 'Ruan' == 'Ruan')
console.log('Felipe' == 'João' || false)
console.log(!(!(true && true)))
console.log(true && true)
console.log(false || false)